model:
  arch: bengali_spelling_correction
  asr_model_name: /mnt/lustre/hanxiao/work/lavis-kaggle/vigc/output/wav2vec_bengali_asr/baseline-0902/best_hf
  model_type: default

datasets:
  # train
  wav2vec_filtered_seg_aug_asr:
    model_name: /mnt/lustre/hanxiao/work/bengali_utils/indic_wav2vec
    sample_ratio: 1
    seg_nums: 3
    ratio: 0.7

  wav2vec_filtered_concat_aug_asr:
    model_name: /mnt/lustre/hanxiao/work/bengali_utils/indic_wav2vec
    sample_ratio: 1
    seg_nums: 2
    ratio: 0.7

  # test
  wav2vec_bengali_asr_test:
    model_name: /mnt/lustre/hanxiao/work/bengali_utils/indic_wav2vec

run:
  runner: runner_iter
  task: whisper_bengali_asr_task
  # optimizer
  lr_sched: "linear_warmup_cosine_lr"
  init_lr: 3e-5
  min_lr: 1e-5
  warmup_lr: 1e-6

  weight_decay: 0.05

  batch_size_train: 8
  batch_size_eval: 8
  accum_grad_iters: 2

  num_workers: 4
  warmup_steps: 1000

  iters_per_inner_epoch: 1000
  max_iters: 30000

  seed: 42
  output_dir: "./output/wav2vec_bengali_asr"

  amp: True
  resume_ckpt_path: null

  evaluate: False
  train_splits: [ "train" ]
  valid_splits: [ "eval" ]

  device: "cuda"
  world_size: 1
  dist_url: "env://"
  distributed: True