model:
  # model_name: /mnt/petrelfs/hanxiao/work/lavis-kaggle/vigc/output/wav2vec_bengali_asr/facebook-1b-finetuned-stage-2/best_hf
  model_name: /mnt/lustre/hanxiao/work/lavis-kaggle/vigc/output/facebook_1b/finetuned-stage3/latest_hf_stage3_0920_dropout_0_8_noise/latest_hf
  load_finetuned: False
  finetuned: ""
  post_process_flag: True
  arch: bengali_1b_wav2vec
  model_type: default
  freeze_encoder: True
  loss_reduction: "sum"
  processor_name: "/mnt/petrelfs/hanxiao/work/bengali_utils/wav2vec2-xls-r-300m-bengali"
#  processor_name: arijitx/wav2vec2-xls-r-300m-bengali

datasets:
  # train
  wav2vec_filtered_seg_aug_asr:
    model_name: /mnt/petrelfs/hanxiao/work/bengali_utils/wav2vec2-large-mms-1b-bengali
    sample_ratio: 1
    seg_nums: 3
    ratio: 0.7

  wav2vec_filtered_concat_aug_asr:
    model_name: /mnt/petrelfs/hanxiao/work/bengali_utils/wav2vec2-large-mms-1b-bengali
    sample_ratio: 1
    seg_nums: 2
    ratio: 0.7

  wav2vec_filtered_concat_seg_aug_asr:
    model_name: /mnt/petrelfs/hanxiao/work/bengali_utils/wav2vec2-large-mms-1b-bengali
    sample_ratio: 1
    concat_seg_nums: 2
    split_seg_nums: 3
    ratio: 0.7

  # test
  wav2vec_bengali_asr_test:
    model_name: /mnt/petrelfs/hanxiao/work/bengali_utils/wav2vec2-large-mms-1b-bengali

run:
  runner: runner_iter
  task: whisper_bengali_asr_task
  # optimizer
  lr_sched: "linear_warmup_cosine_3_long_tail_lr"
  # init_lr: 3e-5
  # min_lr: 1e-5
  # warmup_lr: 1e-6

  init_lr: 1e-5
  min_lr: 5e-6
  warmup_lr: 1e-6

  weight_decay: 0.05

  batch_size_train: 4
  batch_size_eval: 4
  accum_grad_iters: 2

  num_workers: 4
  warmup_steps: 1000

  iters_per_inner_epoch: 1000
  max_iters: 120000
  # max_iters: 240000

  seed: 210
  output_dir: "./output/facebook_1b/finetuned-stage4"

  amp: True
  resume_ckpt_path: null

  evaluate: False
  train_splits: [ "train" ]
  valid_splits: [ "eval" ]

  device: "cuda"
  world_size: 1
  dist_url: "env://"
  distributed: True