datasets:
  wav2vec_bengali_asr_eval:
    model_name: /mnt/petrelfs/hanxiao/work/bengali_utils/wav2vec2-xls-r-300m-bengali
#    model_name: arijitx/wav2vec2-xls-r-300m-bengali
    data_type: audios
    build_info:
      data_root: /mnt/petrelfs/share_data/hanxiao/bengaliai-speech