datasets:
  instruct_blip_okvqa_eval:
    data_type: images
    build_info:
      annotation: /mnt/petrelfs/share_data/zhaozhiyuan/InstructBLIP/OK-VQA/process/okvqa_val_cocoformat.json
      images: /mnt/petrelfs/share_data/zhaozhiyuan/InstructBLIP/OK-VQA/ori/val2014/