model:
  model_name: /mnt/petrelfs/hanxiao/work/lavis-kaggle/vigc/output/wav2vec_bengali_asr/facebook-1b-finetuned-stage-2/best_hf
  load_finetuned: False
  finetuned: ""
  post_process_flag: True
  arch: bengali_1b_wav2vec
  model_type: default
  freeze_encoder: False
  loss_reduction: "mean"
  processor_name: "/mnt/petrelfs/hanxiao/work/bengali_utils/wav2vec2-xls-r-300m-bengali"

#
#model:
#  model_name: /mnt/petrelfs/hanxiao/work/bengali_utils/wav2vec2-xls-r-1b
#  tokenizer_name: /mnt/petrelfs/hanxiao/work/bengali_utils/wav2vec2-large-mms-1b-bengali
#  load_finetuned: False
#  finetuned: ""
#  post_process_flag: True
#  arch: bengali_1b_wav2vec
#  model_type: default
#  freeze_encoder: False
#  loss_reduction: "mean"
#  processor_name: "/mnt/petrelfs/hanxiao/work/bengali_utils/wav2vec2-xls-r-300m-bengali"