model:
  model_name: /mnt/petrelfs/hanxiao/work/bengali_utils/wav2vec2-large-mms-1b-bengali
  load_finetuned: False
  finetuned: ""
  post_process_flag: True
  arch: bengali_umongwav2vec
  model_type: default
  freeze_encoder: False
  loss_reduction: "mean"
  processor_name: "/mnt/petrelfs/hanxiao/work/bengali_utils/wav2vec2-xls-r-300m-bengali"
#  processor_name: arijitx/wav2vec2-xls-r-300m-bengali